#!/bin/bash

echo "Running migrations..."
php /app/vendor/bin/phinx migrate ENV_SOURCE=/app/.env

if [ $? -eq 0 ]; then
    echo "Migrations completed successfully"
else
    echo "Migrations failed"
    exit 1
fi